CREATE DATABASE IF NOT EXISTS dados_saude;
USE dados_saude;

CREATE TABLE IF NOT EXISTS dados_2024 (
   DATA VARCHAR(10),
   REG_ANS INT(6),
   CD_CONTA_CONTABIL VARCHAR(255),
   DESCRICAO VARCHAR(255),
   VL_SALDO_INICIAL DECIMAL(10,2),
   VL_SALDO_FINAL DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS relatorio_cadop (
   Registro_ANS VARCHAR(255),
   CNPJ VARCHAR(14),
   Razao_Social VARCHAR(255),
   Nome_Fantasia VARCHAR(255),
   Modalidade VARCHAR(255),
   Logradouro VARCHAR(255),
   Numero VARCHAR(50),
   Complemento VARCHAR(255),
   Bairro VARCHAR(255),
   Cidade VARCHAR(255),
   UF VARCHAR(255),
   CEP VARCHAR(255),
   DDD VARCHAR(2),
   Telefone VARCHAR(255),
   Fax VARCHAR(255),
   Endereco_eletronico VARCHAR(255),
   Representante VARCHAR(255),
   Cargo_Representante VARCHAR(255),
   Regiao_de_Comercializacao VARCHAR(255),
   Data_Registro_ANS VARCHAR(255)
);

SHOW VARIABLES LIKE 'secure_file_priv';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Relatorio_cadop.csv'
INTO TABLE relatorio_cadop
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/ano_2024.csv'
INTO TABLE dados_2024
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT 
    (d.VL_SALDO_FINAL - d.VL_SALDO_INICIAL) AS diferenca, 
    rc.Razao_Social AS operadora
FROM dados_2024 d
INNER JOIN relatorio_cadop rc ON rc.Registro_ANS = d.REG_ANS
WHERE d.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE DE MEDICO HOSPITALAR'
ORDER BY diferenca DESC
LIMIT 10;

SELECT 
    (d.VL_SALDO_FINAL - d.VL_SALDO_INICIAL) AS diferenca, 
    rc.Razao_Social AS operadora
FROM dados_2024 d
INNER JOIN relatorio_cadop rc ON rc.Registro_ANS = d.REG_ANS
WHERE d.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE DE MEDICO HOSPITALAR'
ORDER BY diferenca DESC
LIMIT 10;
